changed the deploy docs thingy

diff --git a/.github/workflows/deploy_gh_pages.yml b/.github/workflows/deploy_gh_pages.yml
--- a/.github/workflows/deploy_gh_pages.yml
+++ b/.github/workflows/deploy_gh_pages.yml
@@ -45,7 +45,7 @@ jobs:
           restore-keys: |
             ${{ runner.os }}-pip-
             ${{ runner.os }}-
-      - name: Prepare environment
+      - name: Prepare Environment
         uses: conda-incubator/setup-miniconda@v2
         with:
           activate-environment: lwsspy
@@ -60,7 +60,39 @@ jobs:
         run: |
           conda info
           conda list
+      # Standard drop-in approach that should work for most people.
+      - uses: ammaraskar/sphinx-action@master
+        with:
+          docs-folder: "docs/source"
       
+      # Great extra actions to compose with:
+      # Create an artifact of the html output.
+      - uses: actions/upload-artifact@v1
+        with:
+          name: DocumentationHTML
+          path: docs/source/_build/html/
+
+      - name: Commit documentation changes
+        run: |
+          git clone https://github.com/lwsspy/lwsspy.git --branch gh-pages --single-branch gh-pages
+          cp -r docs/source/_build/html/* gh-pages/
+          cd gh-pages
+          touch .nojekyll
+          git config --local user.email "action@github.com"
+          git config --local user.name "GitHub Action"
+          git add .
+          git commit -m "Update documentation" -a || true
+          # The above command will fail if no changes were present, so we ignore
+          # that.
+
+      # Push the changes
+      - name: Push changes
+        uses: ad-m/github-push-action@master
+        with:
+          branch: gh-pages
+          directory: gh-pages
+          github_token: ${{ secrets.GITHUB_TOKEN }}
+          
       # - name: Install dependencies
       #   run: |
       #     python -m pip install --upgrade pip
@@ -74,6 +106,7 @@ jobs:
       #     # has to be done seperately because cartopy is weird
       #     pip install cartopy
       # - name: Debugging information
+      #   shell: bash -l {0}
       #   run: |
       #     echo "github.ref:" ${{github.ref}}
       #     echo "github.event_name:" ${{github.event_name}}
@@ -87,9 +120,10 @@ jobs:
       #     python -V
       #     pip list --not-required
       #     pip list
-      # # Build
+      # Build
       # - uses: ammaraskar/sphinx-problem-matcher@master
       # - name: Build Sphinx docs
+      #   shell: bash -l {0}
       #   run: |
       #     make html # make dirhtml
       #     # This fixes broken copy button icons, as explained in
@@ -100,11 +134,10 @@ jobs:
       #     #   https://github.com/sphinx-doc/sphinx/pull/8524
       #     #   https://github.com/readthedocs/sphinx_rtd_theme/pull/1025
       #     sed -i 's/url_root="#"/url_root=""/' docs/build/html/index.html || true
-      # # The following supports building all branches and combining on
-      # # gh-pages
-
-      # # Clone and set up the old gh-pages branch
+      # The following supports building all branches and combining on gh-pages
+      # Clone and set up the old gh-pages branch
       # - name: Clone old gh-pages
+      #   shell: bash -l {0}
       #   if: ${{ github.event_name == 'push' }}
       #   run: |
       #     set -x
@@ -112,9 +145,10 @@ jobs:
       #     ( git branch gh-pages remotes/origin/gh-pages && git clone . --branch=gh-pages _gh-pages/ ) || mkdir _gh-pages
       #     rm -rf _gh-pages/.git/
       #     mkdir -p _gh-pages/branch/
-      # # If a push and default branch, copy build to _gh-pages/ as the "main"
-      # # deployment.
+      # If a push and default branch, copy build to _gh-pages/ as the "main"
+      # deployment.
       # - name: Copy new build (default branch)
+      #   shell: bash -l {0}
       #   if: |
       #     contains(github.event_name, 'push') &&
       #     contains(github.ref, env.DEFAULT_BRANCH)
@@ -126,8 +160,8 @@ jobs:
       #     # _gh-pages itself.
       #     find _gh-pages/ -mindepth 1 ! -path '_gh-pages/branch*' -delete
       #     rsync -a docs/build/html/ _gh-pages/
-      # # If a push and not on default branch, then copy the build to
-      # # _gh-pages/branch/$brname (transforming '/' into '--')
+      # If a push and not on default branch, then copy the build to
+      # _gh-pages/branch/$brname (transforming '/' into '--')
       # - name: Copy new build (branch)
       #   if: |
       #     contains(github.event_name, 'push') &&
